### ISSUE TITLE
HW SPI APA102 lib

### ISSUE THREAD

**Issue by mkeyno** [robertfoss/esp8266_apa102_bulb#1]
hi, so sorry to draw issue for my question , actually I'm Arduino user and try to make POV with ESP and APA102 ,however after couple of try , I find current version of FastLED does not support HW SPI for LED chip such as APA102, hence I've tried to look proper lib to drive APA102 on ESP, I really appreciated if you could guide me to proper APA102 lib on ESP can be added in Arduino IDE and support HW SPI?

**Comment by robertfoss** [comment]
Hey,

As far as I know there is no HW DMA support for SPI on the ESP8266.

With that being said, do you really need HW SPI? You should be able to run the SPI at 1Mhz. 
You should be able to run 125 APA102 leds at 250Hz.
1Mhz / (32bits/led \* 250Hz) = 125 leds

**Comment by mkeyno** [comment]
yes , it is now  and can get up to 80 MHz, I need to at least 4 to 6 Mbps to run the show and that's why   normal software SPI not work for me ,

**Comment by robertfoss** [comment]
I don't think any library currently supports DMA. You could probably make something based on the I2S, which does have DMA support.
