### ISSUE TITLE
APA201 driver End Frames 

### ISSUE THREAD

**Issue by lorenz24** [robertfoss/esp8266_apa102_bulb#2]
Hi,
I am wondering whether you could do a change on on your driver.
From my experience, with this APA102, the start frame with 32 x 0x00 is important and works.
But the 32 x 0xff is wrong even the datasheet tells you different.

I found out if you send (32 x 0x00) - n*4Byte (LED data) - (32 x 0x00 plus n/2 x 0x00) the frame will be displayed even you send only one time a frame.

For eg.
150 LEDs on one row and you need to light up only the first 100 LEDs.
You send (32 x 0x00) 100 x 4 Byte (57 x 0x00). Only the frst 100 LEDs are on.

If you send (32 x 0x00) 100 x 4 Byte (32 x 0xff) your 101 LED is on white and the
LEDs are on if you send the second frame.

Conclusion: End Frame (32 + n/2) \* 0x00 will allow you sendonlyon times a frame and then+1 LED is off.

**Comment by robertfoss** [comment]
That sounds about right?

Have a look at this driver if you're curious about how it can be done:
https://github.com/nodemcu/nodemcu-firmware/blob/master/app/modules/apa102.c

This probably not the right place for further discussion, feel free to reach out to me on dev@memcpy.io.
